name: ai_chat_app
description: "Zyra - An AI Chat Assistant powered by Google's Gemini"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_markdown: ^0.7.3+1
  delightful_toast: ^1.1.0
  flutter_svg: ^2.0.10+1
  google_generative_ai: ^0.4.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/zyraicon.png"
  remove_alpha_ios: true
